apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Chart.Name }}-monitor
  labels:
    release: monitoring-stack 
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  endpoints:
    - port: http # Khớp với tên port bạn đã định nghĩa trong file service.yaml
      path: /metrics
      interval: 15s